# Generated by Django 6.0.3 on 2026-05-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="guides/photos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("languages", models.CharField(blank=True, max_length=255)),
                ("accepts_children", models.BooleanField(default=True)),
                (
                    "price_adult",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "price_child",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("stars", models.FloatField(default=0.0)),
                (
                    "pending_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_change_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuideReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("rating", models.PositiveIntegerField(default=5)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="guides.guide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuideSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("client_email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("message", models.TextField(blank=True)),
                ("nb_adults", models.PositiveIntegerField(default=1)),
                ("nb_children_under_6", models.PositiveIntegerField(default=0)),
                ("nb_children_over_6", models.PositiveIntegerField(default=0)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="guides.guide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuideWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Crédit"), ("debit", "Débit")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="guides.guide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuideAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "unique_together": {("guide", "date")},
            },
        ),
    ]
