# Generated by Django 5.2.9 on 2026-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidesuggestion",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
