# Generated by Django 5.2.9 on 2026-05-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_guidesuggestion_commission_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="admin_stars",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="guide",
            name="client_stars",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="GuideAdminRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0, help_text="Note de 0 à 5 (pas de 0.5)"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire interne de l'administrateur (non visible par le guide)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_rating",
                        to="guides.guide",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
