# Generated by Django 5.2.9 on 2026-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_guide_admin_stars_guide_client_stars_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                help_text="Langue des notifications envoyées au guide",
                max_length=5,
            ),
        ),
    ]
