# Generated by Django 5.2.9 on 2026-03-12 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/logos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("account_frozen", models.BooleanField(default=False)),
                (
                    "contract_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_month", "1 Mois"),
                            ("3_months", "3 Mois"),
                            ("6_months", "6 Mois"),
                            ("9_months", "9 Mois"),
                            ("12_months", "12 Mois (1 An)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Paiement Mensuel"),
                            ("total", "Paiement Total"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pending_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "konnect_wallet_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
        ),
        migrations.CreateModel(
            name="PartnerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                ("payment_type", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=3, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "konnect_payment_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
