# Generated by Django 5.2.9 on 2026-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
        ),
        migrations.AlterModelOptions(
            name="partnercontract",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contrat Partenaire",
                "verbose_name_plural": "Contrats Partenaires",
            },
        ),
        migrations.RemoveField(
            model_name="partner",
            name="last_login",
        ),
        migrations.AddField(
            model_name="partner",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnercontract",
            name="monthly_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="partnercontract",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="payment_type",
            field=models.CharField(
                choices=[("monthly", "Paiement Mensuel"), ("total", "Paiement Total")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="period",
            field=models.CharField(
                choices=[
                    ("1_month", "1 Mois"),
                    ("3_months", "3 Mois"),
                    ("6_months", "6 Mois"),
                    ("9_months", "9 Mois"),
                    ("12_months", "12 Mois (1 An)"),
                ],
                max_length=20,
            ),
        ),
    ]
