# Generated by Django 5.2.9 on 2026-03-12 20:40

import django.db.models.deletion
import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "partners",
            "0002_alter_partner_options_alter_partnercontract_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Lien d'inscription", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("boosted", "Boosté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_boosted", models.BooleanField(default=False)),
                ("boosted_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement Partenaire",
                "verbose_name_plural": "Événements Partenaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerEventMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="partners/events/",
                        validators=[partners.models.validate_image_or_video],
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="partners.partnerevent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
