# Generated by Django 5.2.9 on 2026-03-13 11:20

import django.db.models.deletion
import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partnerevent_partnereventmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        upload_to="partners/ads/",
                        validators=[partners.models.validate_ad_image],
                    ),
                ),
                ("redirect_url", models.URLField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "price_per_day",
                    models.DecimalField(decimal_places=3, default=5.0, max_digits=8),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "konnect_payment_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                            ("active", "Active"),
                            ("expired", "Expirée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicité Partenaire",
                "verbose_name_plural": "Publicités Partenaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
