# Generated by Django 5.2.9 on 2026-03-21 12:48

import django.db.models.deletion
import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partnerad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=partners.models.generate_coupon_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        help_text="Pourcentage de réduction (ex: 20 = 20%)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("subscription", "Abonnement"),
                            ("content", "Contenu (Events & Ads)"),
                            ("both", "Les deux"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = illimité"),
                ),
                ("current_uses", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="disabled_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_temporarily_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="reactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerad",
            name="discount_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="boost_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="boost_payment_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="contract_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_month", "1 Mois"),
                    ("3_months", "3 Mois"),
                    ("6_months", "6 Mois"),
                    ("10_months", "10 Mois"),
                    ("12_months", "12 Mois (1 An)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partnerad",
            name="price_per_day",
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="period",
            field=models.CharField(
                choices=[
                    ("1_month", "1 Mois"),
                    ("3_months", "3 Mois"),
                    ("6_months", "6 Mois"),
                    ("10_months", "10 Mois"),
                    ("12_months", "12 Mois (1 An)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partnerevent",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unpaid_subscription", "Abonnement impayé"),
                            ("unpaid_ad", "Publicité impayée"),
                            ("email_change", "Changement email en attente"),
                            ("new_partner", "Nouveau partenaire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Admin",
                "verbose_name_plural": "Notifications Admin",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="partnerad",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partners.coupon",
            ),
        ),
    ]
