# Generated by Django 5.2.9 on 2026-03-28 17:24

import django.db.models.deletion
import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0013_alter_city_alternate_names_alter_city_country_and_more"),
        ("guard", "0061_ad_last_clicked_at"),
        (
            "partners",
            "0005_coupon_partner_disabled_at_partner_disabled_reason_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerad",
            name="image",
        ),
        migrations.RemoveField(
            model_name="partnerad",
            name="redirect_url",
        ),
        migrations.AddField(
            model_name="partnerad",
            name="destination_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL de destination. Sera traqué via Short.io.",
            ),
        ),
        migrations.AddField(
            model_name="partnerad",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="Taille requise : 320x50 pixels",
                null=True,
                upload_to="partners/ads/mobile/",
                validators=[partners.models.validate_mobile_image],
            ),
        ),
        migrations.AddField(
            model_name="partnerad",
            name="tablet_image",
            field=models.ImageField(
                blank=True,
                help_text="Taille requise : 728x90 pixels",
                null=True,
                upload_to="partners/ads/tablet/",
                validators=[partners.models.validate_tablet_image],
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_events",
                to="guard.eventcategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_events",
                to="cities_light.city",
                verbose_name="Ville",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description en anglais (HTML autorisé)",
                verbose_name="Description (Anglais)",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="description_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description en français (HTML autorisé)",
                verbose_name="Description (Français)",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="event_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de l'événement"
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_events",
                to="guard.location",
                verbose_name="Lieu",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="price",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="Prix (TND)"
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom de l'événement en anglais",
                max_length=255,
                verbose_name="Titre (Anglais)",
            ),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom de l'événement en français",
                max_length=255,
                verbose_name="Titre (Français)",
            ),
        ),
        migrations.AlterField(
            model_name="partnerad",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
