# Generated by Django 5.2.9 on 2026-02-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0013_alter_city_alternate_names_alter_city_country_and_more"),
        ("guard", "0055_event_boost"),
    ]

    operations = [
        migrations.AddField(
            model_name="publictransport",
            name="fromCity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicTransportsFromCity",
                to="cities_light.city",
                verbose_name="From City",
            ),
        ),
        migrations.AddField(
            model_name="publictransport",
            name="toCity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicTransportsToCity",
                to="cities_light.city",
                verbose_name="To City",
            ),
        ),
    ]
