# Generated by Django 5.2.9 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0056_publictransport_fromcity_publictransport_tocity"),
    ]

    operations = [
        migrations.AddField(
            model_name="publictransport",
            name="is_return",
            field=models.BooleanField(
                default=False,
                help_text="Check this if this is a return journey",
                verbose_name="Is Return Journey",
            ),
        ),
    ]
