# Generated by Django 5.2.9 on 2026-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0057_publictransport_is_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publictransport",
            name="busNumber",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Bus number"
            ),
        ),
    ]
