# Generated by Django 5.2.9 on 2026-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0058_alter_publictransport_busnumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_locations", models.IntegerField(default=0)),
                ("locations_this_month", models.IntegerField(default=0)),
                ("total_events", models.IntegerField(default=0)),
                ("upcoming_events", models.IntegerField(default=0)),
                ("events_this_month", models.IntegerField(default=0)),
                ("total_hikings", models.IntegerField(default=0)),
                ("hikings_this_month", models.IntegerField(default=0)),
                ("total_ads", models.IntegerField(default=0)),
                ("active_ads", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users_30d", models.IntegerField(default=0)),
                ("total_fcm_devices", models.IntegerField(default=0)),
                ("ios_devices", models.IntegerField(default=0)),
                ("android_devices", models.IntegerField(default=0)),
                ("notifications_sent_24h", models.IntegerField(default=0)),
                ("notifications_failed_24h", models.IntegerField(default=0)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("error_count_24h", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Dashboard Statistics",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("location_created", "Location créée"),
                            ("location_updated", "Location modifiée"),
                            ("event_created", "Event créée"),
                            ("event_updated", "Event modifiée"),
                            ("hiking_created", "Hiking créée"),
                            ("hiking_updated", "Hiking modifiée"),
                            ("ad_created", "Publicité créée"),
                            ("notification_sent", "Notification envoyée"),
                            ("notification_failed", "Notification échouée"),
                            ("error_occurred", "Erreur système"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                (
                    "entity_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="guard_activ_activit_82fc3a_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "-timestamp"],
                        name="guard_activ_entity__133196_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("device_count_attempted", models.IntegerField(default=0)),
                ("device_count_succeeded", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyée"),
                            ("delivered", "Livrée"),
                            ("failed", "Échouée"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["status", "-timestamp"],
                        name="guard_notif_status_3eb13b_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-timestamp"],
                        name="guard_notif_notific_1e6ac6_idx",
                    ),
                ],
            },
        ),
    ]
