# Generated by Django 5.2.9 on 2026-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0059_dashboardstatistics_activitylog_notificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("ad", "Ad"), ("event", "Event")], max_length=10
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("short_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "clicked_at"],
                        name="guard_click_content_d83083_idx",
                    )
                ],
            },
        ),
    ]
