# Generated by Django 5.2.9 on 2026-03-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0060_add_click_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="last_clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
