# Generated by Django 5.2.9 on 2026-04-29 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0061_ad_last_clicked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Verification Token",
                "verbose_name_plural": "Email Verification Tokens",
            },
        ),
        migrations.CreateModel(
            name="LegacyPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "image",
                    models.ImageField(upload_to="partners/", verbose_name="Image"),
                ),
                ("link", models.URLField(verbose_name="Link")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="legacy_partners",
                        to="guard.location",
                        verbose_name="Locations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_tokens",
                to="guard.legacypartner",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_locations",
                to="guard.legacypartner",
                verbose_name="Partner",
            ),
        ),
    ]
