# Generated by Django 5.2.9 on 2026-04-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0062_add_partner_to_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_records",
                        to="guard.ad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Click Record",
                "verbose_name_plural": "Ad Click Records",
            },
        ),
        migrations.CreateModel(
            name="EventClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_records",
                        to="guard.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Click Record",
                "verbose_name_plural": "Event Click Records",
            },
        ),
    ]
