# Generated by Django 6.0.3 on 2026-05-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0063_adclick_eventclick"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="legacypartner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_partner_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
    ]
